// Auto-generated by Sew — TypeScript WASM bindings

let wasmInstance;
let wasmMemory;

const files = {
  "/": { type: "dir", contents: new Uint8Array(0) }
};

function resolvePath(dirPath, path) {
  if (path.startsWith("/")) return path;
  const parts = (dirPath + "/" + path).split("/");
  const stack = [];
  for (const part of parts) {
    if (!part || part === ".") continue;
    if (part === "..") { stack.pop(); }
    else { stack.push(part); }
  }
  return "/" + stack.join("/");
}

const fds = new Map([
  [0, { path: "/dev/stdin", pos: 0, flags: 0 }],
  [1, { path: "/dev/stdout", pos: 0, flags: 0 }],
  [2, { path: "/dev/stderr", pos: 0, flags: 0 }],
  [3, { path: "/", pos: 0, flags: 0 }]
]);
let nextFd = 4;

const gpuRegistry = new Map();
let nextGpuId = 1;
function regGpu(obj) {
  const id = nextGpuId++;
  gpuRegistry.set(id, obj);
  return id;
}

let cmdArgs = [];

const callbackRegistry = new Map();
export function call_js_callback(cbId, argPtr) {
  const cb = callbackRegistry.get(cbId);
  if (cb) {
    cb(argPtr);
  }
}
export function call_js_callback_bool(cbId, argPtr) {
  const cb = callbackRegistry.get(cbId);
  if (cb) {
    return cb(argPtr) ? 1 : 0;
  }
  return 0;
}
export function call_js_callback_ptr(cbId, argPtr) {
  const cb = callbackRegistry.get(cbId);
  if (cb) {
    return cb(argPtr) || 0;
  }
  return 0;
}

export async function init(wasmUrl, args = []) {
  cmdArgs = [wasmUrl, ...args];
  const response = await fetch(wasmUrl);
  const buffer = await response.arrayBuffer();
  wasmMemory = new WebAssembly.Memory({ initial: 256 });
  
  const imports = {
    env: {
      memory: wasmMemory,
      call_js_callback: call_js_callback,
      call_js_callback_bool: call_js_callback_bool,
      call_js_callback_ptr: call_js_callback_ptr,
      
      // ─── xic fetch API ──────────────────────────────────────────────────
      xic_fetch_get: (urlPtr, onSuccessPtr, onErrorPtr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, urlPtr + len, 1)[0] !== 0) len++;
        const url = new TextDecoder().decode(new Uint8Array(memory.buffer, urlPtr, len));
        
        fetch(url)
          .then(res => res.arrayBuffer())
          .then(buf => {
            const bytes = new Uint8Array(buf);
            const mallocPtr = wasmInstance.exports.malloc(bytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, bytes.length + 1);
            dest.set(bytes);
            dest[bytes.length] = 0;
            wasmInstance.exports.__indirect_function_table.get(onSuccessPtr)(mallocPtr, bytes.length);
            wasmInstance.exports.free(mallocPtr);
          })
          .catch(err => {
            const errBytes = new TextEncoder().encode(err.message || String(err));
            const mallocPtr = wasmInstance.exports.malloc(errBytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, errBytes.length + 1);
            dest.set(errBytes);
            dest[errBytes.length] = 0;
            wasmInstance.exports.__indirect_function_table.get(onErrorPtr)(mallocPtr);
            wasmInstance.exports.free(mallocPtr);
          });
      },
      
      xic_fetch_post: (urlPtr, bodyPtr, onSuccessPtr, onErrorPtr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, urlPtr + len, 1)[0] !== 0) len++;
        const url = new TextDecoder().decode(new Uint8Array(memory.buffer, urlPtr, len));
        
        let bodyLen = 0;
        while (new Uint8Array(memory.buffer, bodyPtr + bodyLen, 1)[0] !== 0) bodyLen++;
        const body = new TextDecoder().decode(new Uint8Array(memory.buffer, bodyPtr, bodyLen));
        
        fetch(url, { method: "POST", body })
          .then(res => res.arrayBuffer())
          .then(buf => {
            const bytes = new Uint8Array(buf);
            const mallocPtr = wasmInstance.exports.malloc(bytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, bytes.length + 1);
            dest.set(bytes);
            dest[bytes.length] = 0;
            wasmInstance.exports.__indirect_function_table.get(onSuccessPtr)(mallocPtr, bytes.length);
            wasmInstance.exports.free(mallocPtr);
          })
          .catch(err => {
            const errBytes = new TextEncoder().encode(err.message || String(err));
            const mallocPtr = wasmInstance.exports.malloc(errBytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, errBytes.length + 1);
            dest.set(errBytes);
            dest[errBytes.length] = 0;
            wasmInstance.exports.__indirect_function_table.get(onErrorPtr)(mallocPtr);
            wasmInstance.exports.free(mallocPtr);
          });
      },

      // ─── WebGPU Bridge API ──────────────────────────────────────────────
      wgpu_request_adapter: (onAdapterReady) => {
        if (!navigator.gpu) {
          console.error("WebGPU is not supported on this browser (navigator.gpu is undefined).");
          wasmInstance.exports.__indirect_function_table.get(onAdapterReady)(0);
          return;
        }
        navigator.gpu.requestAdapter().then(adapter => {
          if (!adapter) {
            console.error("WebGPU requestAdapter() returned null (no GPU adapters available).");
            wasmInstance.exports.__indirect_function_table.get(onAdapterReady)(0);
            return;
          }
          const id = regGpu(adapter);
          wasmInstance.exports.__indirect_function_table.get(onAdapterReady)(id);
        }).catch(err => {
          console.error("WebGPU error requesting adapter:", err);
          wasmInstance.exports.__indirect_function_table.get(onAdapterReady)(0);
        });
      },
      
      wgpu_adapter_request_device: (adapterId, onDeviceReady) => {
        const adapter = gpuRegistry.get(adapterId);
        adapter.requestDevice().then((device) => {
          const id = regGpu(device);
          wasmInstance.exports.__indirect_function_table.get(onDeviceReady)(id);
        });
      },
      
      wgpu_device_create_shader_module: (deviceId, wgslCodePtr) => {
        const device = gpuRegistry.get(deviceId);
        const memory = wasmInstance.exports.memory || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, wgslCodePtr + len, 1)[0] !== 0) len++;
        const code = new TextDecoder().decode(new Uint8Array(memory.buffer, wgslCodePtr, len));
        const sm = device.createShaderModule({ code });
        return regGpu(sm);
      },
      
      wgpu_device_create_pipeline: (deviceId, shaderModuleId, entryPointPtr) => {
        const device = gpuRegistry.get(deviceId);
        const sm = gpuRegistry.get(shaderModuleId);
        const memory = wasmInstance.exports.memory || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, entryPointPtr + len, 1)[0] !== 0) len++;
        const entryPoint = new TextDecoder().decode(new Uint8Array(memory.buffer, entryPointPtr, len));
        const pipeline = device.createComputePipeline({
          layout: "auto",
          compute: { module: sm, entryPoint }
        });
        return regGpu(pipeline);
      },
      
      wgpu_device_run_compute: (deviceId, pipelineId, bufferId, workgroupCountX) => {
        const device = gpuRegistry.get(deviceId);
        const pipeline = gpuRegistry.get(pipelineId);
        // Simple compute shader execution interface
      },
      wgpu_configure_canvas: (deviceId, canvasIdPtr) => {
        const device = gpuRegistry.get(deviceId);
        const memory = wasmInstance.exports.memory || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, canvasIdPtr + len, 1)[0] !== 0) len++;
        const canvasId = new TextDecoder().decode(new Uint8Array(memory.buffer, canvasIdPtr, len));
        const canvas = document.getElementById(canvasId) ;
        const context = canvas.getContext('webgpu');
        const format = navigator.gpu.getPreferredCanvasFormat();
        context.configure({ device, format, alphaMode: 'opaque' });
        return regGpu(context);
      },
      wgpu_clear_canvas: (deviceId, contextId, r, g, b, a) => {
        const device = gpuRegistry.get(deviceId);
        const context = gpuRegistry.get(contextId);
        const commandEncoder = device.createCommandEncoder();
        const textureView = context.getCurrentTexture().createView();
        const renderPassDescriptor = {
          colorAttachments: [{
            view: textureView,
            clearValue: { r, g, b, a },
            loadOp: 'clear',
            storeOp: 'store'
          }]
        };
        const passEncoder = commandEncoder.beginRenderPass(renderPassDescriptor);
        passEncoder.end();
        device.queue.submit([commandEncoder.finish()]);
      },
      js_request_animation_frame: (callbackPtr) => {
        requestAnimationFrame(() => {
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)();
        });
      }
    },
    
    // ─── WASI Snapshot Preview 1 Specification Host ──────────────────────
    wasi_snapshot_preview1: {
      proc_exit: (code) => {
        throw new Error(`Exit code: ${code}`);
      },
      
      environ_sizes_get: (environ_count_ptr, environ_size_ptr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint32(environ_count_ptr, 0, true);
        view.setUint32(environ_size_ptr, 0, true);
        return 0;
      },
      
      environ_get: () => 0,
      
      args_sizes_get: (argc_ptr, argv_len_ptr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint32(argc_ptr, cmdArgs.length, true);
        
        let totalSize = 0;
        const encoder = new TextEncoder();
        for (const arg of cmdArgs) {
          totalSize += encoder.encode(arg).length + 1;
        }
        view.setUint32(argv_len_ptr, totalSize, true);
        return 0;
      },
      
      args_get: (argv_ptr, argv_buf_ptr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        const bytes = new Uint8Array(memory.buffer);
        const encoder = new TextEncoder();
        
        let currentOffset = argv_buf_ptr;
        for (let i = 0; i < cmdArgs.length; i++) {
          view.setUint32(argv_ptr + i * 4, currentOffset, true);
          const encoded = encoder.encode(cmdArgs[i]);
          bytes.set(encoded, currentOffset);
          bytes[currentOffset + encoded.length] = 0;
          currentOffset += encoded.length + 1;
        }
        return 0;
      },
      
      fd_prestat_get: (fd, prestat_ptr) => {
        if (fd === 3) {
          const memory = wasmInstance.exports.memory || wasmMemory;
          const view = new DataView(memory.buffer);
          view.setUint8(prestat_ptr, 0); // pr_type = preopen_dir (0)
          view.setUint32(prestat_ptr + 4, 1, true); // "/" length = 1
          return 0;
        }
        return 8; // EBADF
      },
      
      fd_prestat_dir_name: (fd, path_ptr, path_len) => {
        if (fd === 3) {
          const memory = wasmInstance.exports.memory || wasmMemory;
          const bytes = new Uint8Array(memory.buffer, path_ptr, path_len);
          bytes.set(new TextEncoder().encode("/"));
          return 0;
        }
        return 8; // EBADF
      },
      
      fd_fdstat_get: (fd, fdstat_ptr) => {
        const desc = fds.get(fd);
        if (!desc) return 8; // EBADF
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint8(fdstat_ptr, desc.path === "/" ? 3 : 4);
        view.setUint16(fdstat_ptr + 2, 0, true);
        return 0;
      },
      
      fd_write: (fd, iovs, iovs_len, nwrittenOutPtr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        let totalWritten = 0;
        let str = "";
        
        for (let i = 0; i < iovs_len; i++) {
          const bufPtr = view.getUint32(iovs + i * 8, true);
          const bufLen = view.getUint32(iovs + i * 8 + 4, true);
          const bytes = new Uint8Array(memory.buffer, bufPtr, bufLen);
          
          if (fd === 1 || fd === 2) {
            str += new TextDecoder().decode(bytes);
          } else {
            const desc = fds.get(fd);
            if (!desc) return 8; // EBADF
            let file = files[desc.path];
            if (!file) {
              file = { type: "file", contents: new Uint8Array(0) };
              files[desc.path] = file;
            }
            const newContents = new Uint8Array(desc.pos + bufLen);
            newContents.set(file.contents);
            newContents.set(bytes, desc.pos);
            file.contents = newContents;
            desc.pos += bufLen;
          }
          totalWritten += bufLen;
        }
        
        if (fd === 1 || fd === 2) {
          if (typeof process !== "undefined" && process.stdout && process.stdout.write) {
            process.stdout.write(str);
          } else {
            console.log(str);
          }
        }
        
        view.setUint32(nwrittenOutPtr, totalWritten, true);
        return 0;
      },
      
      fd_read: (fd, iovs, iovs_len, nreadOutPtr) => {
        const desc = fds.get(fd);
        if (!desc) return 8; // EBADF
        const file = files[desc.path];
        if (!file || file.type !== "file") return 44; // ENOENT
        
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        let totalRead = 0;
        
        for (let i = 0; i < iovs_len; i++) {
          const bufPtr = view.getUint32(iovs + i * 8, true);
          const bufLen = view.getUint32(iovs + i * 8 + 4, true);
          
          if (desc.pos >= file.contents.length) break;
          const remaining = file.contents.length - desc.pos;
          const toRead = Math.min(bufLen, remaining);
          const dest = new Uint8Array(memory.buffer, bufPtr, toRead);
          dest.set(file.contents.subarray(desc.pos, desc.pos + toRead));
          desc.pos += toRead;
          totalRead += toRead;
        }
        
        view.setUint32(nreadOutPtr, totalRead, true);
        return 0;
      },
      
      fd_seek: (fd, offset_low, offset_high, whence, newoffset_ptr) => {
        const desc = fds.get(fd);
        if (!desc) return 8;
        const file = files[desc.path];
        if (!file) return 8;
        
        const size = file.contents.length;
        if (whence === 0) desc.pos = offset_low;
        else if (whence === 1) desc.pos += offset_low;
        else if (whence === 2) desc.pos = size + offset_low;
        
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint32(newoffset_ptr, desc.pos, true);
        view.setUint32(newoffset_ptr + 4, 0, true);
        return 0;
      },
      
      fd_close: (fd) => {
        if (!fds.has(fd)) return 8;
        fds.delete(fd);
        return 0;
      },
      
      path_open: (dirfd, dirflags, path_ptr, path_len, oflags, fs_rights_base, fs_rights_inheriting, fdflags, fd_ptr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        const pathBytes = new Uint8Array(memory.buffer, path_ptr, path_len);
        const relPath = new TextDecoder().decode(pathBytes);
        const dirDesc = fds.get(dirfd);
        if (!dirDesc) return 8;
        const fullPath = resolvePath(dirDesc.path, relPath);
        
        const O_CREAT = (oflags & 1) !== 0;
        const O_TRUNC = (oflags & 8) !== 0;
        
        let file = files[fullPath];
        if (!file) {
          if (O_CREAT) {
            file = { type: "file", contents: new Uint8Array(0) };
            files[fullPath] = file;
          } else {
            return 44; // ENOENT
          }
        } else if (O_TRUNC) {
          file.contents = new Uint8Array(0);
        }
        
        const newFd = nextFd++;
        fds.set(newFd, { path: fullPath, pos: 0, flags: fdflags });
        view.setUint32(fd_ptr, newFd, true);
        return 0;
      },
      
      path_filestat_get: (dirfd, flags, path_ptr, path_len, stat_ptr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        const pathBytes = new Uint8Array(memory.buffer, path_ptr, path_len);
        const relPath = new TextDecoder().decode(pathBytes);
        const dirDesc = fds.get(dirfd);
        if (!dirDesc) return 8;
        const fullPath = resolvePath(dirDesc.path, relPath);
        
        const file = files[fullPath];
        if (!file) return 44;
        
        view.setUint8(stat_ptr + 16, file.type === "dir" ? 3 : 4);
        view.setBigUint64(stat_ptr + 24, BigInt(file.contents ? file.contents.length : 0), true);
        return 0;
      },
      
      random_get: (buf_ptr, buf_len) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const bytes = new Uint8Array(memory.buffer, buf_ptr, buf_len);
        if (typeof crypto !== "undefined" && crypto.getRandomValues) {
          crypto.getRandomValues(bytes);
        } else {
          for (let i = 0; i < buf_len; i++) bytes[i] = Math.floor(Math.random() * 256);
        }
        return 0;
      },
      
      clock_time_get: (id, precision, time_ptr) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setBigUint64(time_ptr, BigInt(Math.floor(performance.now() * 1e6)), true);
        return 0;
      }
    }
  };
  
  const { instance } = await WebAssembly.instantiate(buffer, imports);
  wasmInstance = instance;
}

export function getExports() {
  return wasmInstance.exports;
}
