// Auto-generated by Sew — TypeScript WASM bindings

let wasmInstance: any;
let wasmMemory: any;
let exports: any;

const files: Record<string, { type: string; contents: Uint8Array }> = {
  "/": { type: "dir", contents: new Uint8Array(0) }
};

function resolvePath(dirPath: string, path: string): string {
  if (path.startsWith("/")) return path;
  const parts = (dirPath + "/" + path).split("/");
  const stack: string[] = [];
  for (const part of parts) {
    if (!part || part === ".") continue;
    if (part === "..") { stack.pop(); }
    else { stack.push(part); }
  }
  return "/" + stack.join("/");
}

const fds = new Map<number, { path: string; pos: number; flags: number }>([
  [0, { path: "/dev/stdin", pos: 0, flags: 0 }],
  [1, { path: "/dev/stdout", pos: 0, flags: 0 }],
  [2, { path: "/dev/stderr", pos: 0, flags: 0 }],
  [3, { path: "/", pos: 0, flags: 0 }]
]);
let nextFd = 4;

const gpuRegistry = new Map<number, any>();
let nextGpuId = 1;
function regGpu(obj: any): number {
  const id = nextGpuId++;
  gpuRegistry.set(id, obj);
  return id;
}

let cmdArgs: string[] = [];

const callbackRegistry = new Map<number, Function>();
export function call_js_callback(cbId: number, argPtr: number) {
  const cb = callbackRegistry.get(cbId);
  if (cb) {
    cb(argPtr);
  }
}
export function call_js_callback_bool(cbId: number, argPtr: number): number {
  const cb = callbackRegistry.get(cbId);
  if (cb) {
    return cb(argPtr) ? 1 : 0;
  }
  return 0;
}
export function call_js_callback_ptr(cbId: number, argPtr: number): number {
  const cb = callbackRegistry.get(cbId);
  if (cb) {
    return cb(argPtr) || 0;
  }
  return 0;
}

export async function init(wasmUrl: string, args: string[] = []): Promise<void> {
  cmdArgs = [wasmUrl, ...args];
  const response = await fetch(wasmUrl);
  const buffer = await response.arrayBuffer();
  wasmMemory = new WebAssembly.Memory({ initial: 256 });
  
  const imports = {
    env: {
      memory: wasmMemory,
      call_js_callback: call_js_callback,
      call_js_callback_bool: call_js_callback_bool,
      call_js_callback_ptr: call_js_callback_ptr,

      _ZN2Xi4Time5sleepEd: () => { },
      _ZN2Xi16secureRandomFillERN10Collection6StringEm: (strPtr: number, len: number) => {
        if (typeof crypto !== 'undefined' && crypto.getRandomValues && len > 0) {
          const memory = exports || wasmMemory;
          const dataView = new Uint32Array(memory.buffer, strPtr, 1);
          const char_data_ptr = dataView[0];
          const view = new Uint8Array(memory.buffer, char_data_ptr, len);
          crypto.getRandomValues(view);
        }
      },
      _ZN2Xi10randomSeedEN10Collection6StringE: () => { },
      __syscall_unlinkat: () => 0,
      __syscall_bind: () => 0,
      __syscall_getsockname: () => 0,
      __syscall_recvfrom: () => 0,
      __syscall_sendto: () => 0,
      __syscall_socket: () => 0,

      // ─── xic fetch API ──────────────────────────────────────────────────
      xic_fetch_get: (urlPtr: number, onSuccessPtr: number, onErrorPtr: number) => {
        const memory = exports || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, urlPtr + len, 1)[0] !== 0) len++;
        const url = new TextDecoder().decode(new Uint8Array(memory.buffer, urlPtr, len));

        fetch(url)
          .then(res => res.arrayBuffer())
          .then(buf => {
            const bytes = new Uint8Array(buf);
            const mallocPtr = exports.malloc(bytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, bytes.length + 1);
            dest.set(bytes);
            dest[bytes.length] = 0;
            exports.__indirect_function_table.get(onSuccessPtr)(mallocPtr, bytes.length);
            exports.free(mallocPtr);
          })
          .catch(err => {
            const errBytes = new TextEncoder().encode(err.message || String(err));
            const mallocPtr = exports.malloc(errBytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, errBytes.length + 1);
            dest.set(errBytes);
            dest[errBytes.length] = 0;
            exports.__indirect_function_table.get(onErrorPtr)(mallocPtr);
            exports.free(mallocPtr);
          });
      },

      xic_fetch_post: (urlPtr: number, bodyPtr: number, onSuccessPtr: number, onErrorPtr: number) => {
        const memory = exports || wasmMemory;
        let len = 0;
        while (new Uint8Array(memory.buffer, urlPtr + len, 1)[0] !== 0) len++;
        const url = new TextDecoder().decode(new Uint8Array(memory.buffer, urlPtr, len));

        let bodyLen = 0;
        while (new Uint8Array(memory.buffer, bodyPtr + bodyLen, 1)[0] !== 0) bodyLen++;
        const body = new TextDecoder().decode(new Uint8Array(memory.buffer, bodyPtr, bodyLen));

        fetch(url, { method: "POST", body })
          .then(res => res.arrayBuffer())
          .then(buf => {
            const bytes = new Uint8Array(buf);
            const mallocPtr = exports.malloc(bytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, bytes.length + 1);
            dest.set(bytes);
            dest[bytes.length] = 0;
            exports.__indirect_function_table.get(onSuccessPtr)(mallocPtr, bytes.length);
            exports.free(mallocPtr);
          })
          .catch(err => {
            const errBytes = new TextEncoder().encode(err.message || String(err));
            const mallocPtr = exports.malloc(errBytes.length + 1);
            const dest = new Uint8Array(memory.buffer, mallocPtr, errBytes.length + 1);
            dest.set(errBytes);
            dest[errBytes.length] = 0;
            exports.__indirect_function_table.get(onErrorPtr)(mallocPtr);
            exports.free(mallocPtr);
          });
      },

      // ─── Standard WebGPU C API to JS Host Bridge ──────────────────────
      wgpuRequestAdapter: (canvasIdPtr: number, callbackPtr: number, userdata: number) => {
        if (!navigator.gpu) {
          console.error("WebGPU not supported on this browser.");
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)(0, userdata);
          return;
        }
        const canvasId = readString(canvasIdPtr);
        navigator.gpu.requestAdapter().then(adapter => {
          if (!adapter) {
            wasmInstance.exports.__indirect_function_table.get(callbackPtr)(0, userdata);
            return;
          }
          const id = regGpu(adapter);
          const canvas = document.getElementById(canvasId);
          if (canvas) {
            (adapter as any)._canvas = canvas;
          }
          // Pass 2 arguments: (adapterId, userdata)
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)(id, userdata);
        }).catch((err) => {
          console.error("Adapter request failed:", err);
          // Pass 2 arguments: (0, userdata)
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)(0, userdata);
        });
      },

      wgpuAdapterRequestDevice: (adapterId: number, callbackPtr: number, userdata: number) => {
        const adapter = gpuRegistry.get(adapterId);
        adapter.requestDevice().then((device: any) => {
          const id = regGpu(device);
          if (adapter._canvas) {
            const context = adapter._canvas.getContext("webgpu");
            const format = navigator.gpu.getPreferredCanvasFormat();
            context.configure({ device, format, alphaMode: "opaque" });
            device._contextId = regGpu(context);
          }
          // Pass 2 arguments: (deviceId, userdata)
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)(id, userdata);
        }).catch((err) => {
          console.error("Device request failed:", err);
          // Pass 2 arguments: (0, userdata)
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)(0, userdata);
        });
      },
      wgpuDeviceGetQueue: (deviceId: number) => {
        const device = gpuRegistry.get(deviceId);
        return regGpu(device.queue);
      },

      wgpuDeviceCreateShaderModule: (deviceId: number, descriptorPtr: number) => {
        const device = gpuRegistry.get(deviceId);
        const activeMemory = exports?.memory?.buffer || wasmMemory.buffer;
        const view = new DataView(activeMemory);
        const chainPtr = view.getUint32(descriptorPtr, true);
        const codePtr = view.getUint32(chainPtr, true);
        const code = readString(codePtr);
        const sm = device.createShaderModule({ code });
        return regGpu(sm);
      },

      wgpuDeviceCreateBuffer: (deviceId: number, descriptorPtr: number) => {
        const device = gpuRegistry.get(deviceId);
        const activeMemory = exports?.memory?.buffer || wasmMemory.buffer;
        const view = new DataView(activeMemory);
        const labelPtr = view.getUint32(descriptorPtr, true);
        const usage = view.getUint32(descriptorPtr + 4, true);
        const size = Number(view.getBigUint64(descriptorPtr + 8, true));
        const mappedAtCreation = view.getUint8(descriptorPtr + 16) !== 0;
        const buffer = device.createBuffer({
          label: labelPtr ? readString(labelPtr) : undefined,
          size,
          usage,
          mappedAtCreation
        });
        return regGpu(buffer);
      },

      wgpuBufferWrite: (queueId: number, bufferId: number, bufferOffset: number, dataPtr: number, size: number) => {
        const queue = gpuRegistry.get(queueId);
        const buffer = gpuRegistry.get(bufferId);
        const view = new Uint8Array(wasmMemory.buffer, dataPtr, size);
        queue.writeBuffer(buffer, bufferOffset, view, 0, size);
      },

      wgpuBufferDestroy: (bufferId: number) => {
        const buffer = gpuRegistry.get(bufferId);
        if (buffer) {
          buffer.destroy();
          gpuRegistry.delete(bufferId);
        }
      },

      wgpuDeviceCreateBindGroupLayout: (deviceId: number, descriptorPtr: number) => {
        const device = gpuRegistry.get(deviceId);
        const activeMemory = exports?.memory?.buffer || wasmMemory.buffer;
        const view = new DataView(activeMemory);
        const labelPtr = view.getUint32(descriptorPtr, true);
        const entryCount = view.getUint32(descriptorPtr + 4, true);
        const entriesPtr = view.getUint32(descriptorPtr + 8, true);
        const entries: any[] = [];
        for (let i = 0; i < entryCount; i++) {
          const entryOffset = entriesPtr + i * 8;
          entries.push({
            binding: view.getUint32(entryOffset, true),
            visibility: view.getUint32(entryOffset + 4, true),
            buffer: {}
          });
        }
        const bgl = device.createBindGroupLayout({
          label: labelPtr ? readString(labelPtr) : undefined,
          entries
        });
        return regGpu(bgl);
      },

      wgpuDeviceCreateBindGroup: (deviceId: number, descriptorPtr: number) => {
        const device = gpuRegistry.get(deviceId);
        const activeMemory = exports?.memory?.buffer || wasmMemory.buffer;
        const view = new DataView(activeMemory);
        const labelPtr = view.getUint32(descriptorPtr, true);
        const layoutId = view.getUint32(descriptorPtr + 4, true);
        const entryCount = view.getUint32(descriptorPtr + 8, true);
        const entriesPtr = view.getUint32(descriptorPtr + 12, true);
        const layout = gpuRegistry.get(layoutId);
        const entries: any[] = [];
        for (let i = 0; i < entryCount; i++) {
          const entryOffset = entriesPtr + i * 28;
          const binding = view.getUint32(entryOffset, true);
          const bufferId = view.getUint32(entryOffset + 4, true);
          const offset = Number(view.getBigUint64(entryOffset + 8, true));
          const size = Number(view.getBigUint64(entryOffset + 16, true));
          const resource: any = {
            buffer: gpuRegistry.get(bufferId),
            offset,
            size
          };
          entries.push({ binding, resource });
        }
        const bg = device.createBindGroup({
          label: labelPtr ? readString(labelPtr) : undefined,
          layout,
          entries
        });
        return regGpu(bg);
      },

      wgpuDeviceCreateCommandEncoder: (deviceId: number, labelPtr: number) => {
        const device = gpuRegistry.get(deviceId);
        const encoder = device.createCommandEncoder({
          label: labelPtr ? readString(labelPtr) : undefined
        });

        // FIX: Propagate the context ID from the device to the encoder
        encoder._contextId = device._contextId;

        return regGpu(encoder);
      },

      wgpuCommandEncoderBeginComputePass: (encoderId: number, labelPtr: number) => {
        const encoder = gpuRegistry.get(encoderId);
        const pass = encoder.beginComputePass({
          label: labelPtr ? readString(labelPtr) : undefined
        });
        return regGpu(pass);
      },

      wgpuComputePassSetPipeline: (passId: number, pipelineId: number) => {
        const pass = gpuRegistry.get(passId);
        const pipeline = gpuRegistry.get(pipelineId);
        pass.setPipeline(pipeline);
      },

      wgpuComputePassSetBindGroup: (passId: number, groupIndex: number, bindGroupId: number, dynamicOffsetCount: number, dynamicOffsetsPtr: number) => {
        const pass = gpuRegistry.get(passId);
        const bg = gpuRegistry.get(bindGroupId);
        let offsets: number[] | undefined = undefined;
        if (dynamicOffsetCount > 0 && dynamicOffsetsPtr) {
          offsets = Array.from(new Uint32Array(wasmMemory.buffer, dynamicOffsetsPtr, dynamicOffsetCount));
        }
        pass.setBindGroup(groupIndex, bg, offsets);
      },

      wgpuComputePassDispatchWorkgroups: (passId: number, x: number, y: number, z: number) => {
        const pass = gpuRegistry.get(passId);
        pass.dispatchWorkgroups(x, y, z);
      },

      wgpuComputePassEnd: (passId: number) => {
        const pass = gpuRegistry.get(passId);
        pass.end();
        gpuRegistry.delete(passId);
      },

      wgpuCommandEncoderFinish: (encoderId: number, labelPtr: number) => {
        const encoder = gpuRegistry.get(encoderId);
        const cb = encoder.finish({
          label: labelPtr ? readString(labelPtr) : undefined
        });
        gpuRegistry.delete(encoderId);
        return regGpu(cb);
      },

      wgpuQueueSubmit: (queueId: number, commandCount: number, commandsPtr: number) => {
        const queue = gpuRegistry.get(queueId);
        // Dynamically get the active memory buffer
        const activeMemory = exports?.memory?.buffer || wasmMemory.buffer;
        const view = new Uint32Array(activeMemory, commandsPtr, commandCount);
        const commandBuffers: any[] = [];
        for (let i = 0; i < commandCount; i++) {
          const cb = gpuRegistry.get(view[i]);
          commandBuffers.push(cb);
          gpuRegistry.delete(view[i]);
        }
        queue.submit(commandBuffers);
      },

      jsRequestAnimationFrame: (callbackPtr: number) => {
        requestAnimationFrame(() => {
          wasmInstance.exports.__indirect_function_table.get(callbackPtr)();
        });
      },

      wgpuCommandEncoderBeginRenderPass: (encoderId: number, descriptorPtr: number) => {
        const encoder = gpuRegistry.get(encoderId);
        const activeMemory = exports?.memory?.buffer || wasmMemory.buffer;
        const view = new DataView(activeMemory);
        const colorAttachmentCount = view.getUint32(descriptorPtr, true);
        const colorAttachmentsPtr = view.getUint32(descriptorPtr + 4, true);
        const colorAttachments: any[] = [];
        for (let i = 0; i < colorAttachmentCount; i++) {
          const offset = colorAttachmentsPtr + i * 48;
          const texViewId = view.getUint32(offset, true);
          const resolveTargetId = view.getUint32(offset + 4, true);
          const loadOp = view.getUint32(offset + 8, true);
          const storeOp = view.getUint32(offset + 12, true);
          const r = view.getFloat64(offset + 16, true);
          const g = view.getFloat64(offset + 24, true);
          const b = view.getFloat64(offset + 32, true);
          const a = view.getFloat64(offset + 40, true);
          let textureView;
          if (texViewId === 0) {
            const context = gpuRegistry.get(encoder._contextId || encoder.device?._contextId);
            textureView = context.getCurrentTexture().createView();
          } else {
            textureView = gpuRegistry.get(texViewId);
          }
          colorAttachments.push({
            view: textureView,
            resolveTarget: resolveTargetId ? gpuRegistry.get(resolveTargetId) : undefined,
            clearValue: { r, g, b, a },
            loadOp: loadOp === 1 ? 'clear' : 'load',
            storeOp: storeOp === 1 ? 'store' : 'discard'
          });
        }
        const pass = encoder.beginRenderPass({ colorAttachments });
        return regGpu(pass);
      },

      wgpuRenderPassEncoderEnd: (passId: number) => {
        const pass = gpuRegistry.get(passId);
        pass.end();
        gpuRegistry.delete(passId);
      },
    },
    
    wasi_snapshot_preview1: {
      proc_exit: (code: number) => {
        throw new Error(`Exit code: ${code}`);
      },
      
      environ_sizes_get: (environ_count_ptr: number, environ_size_ptr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint32(environ_count_ptr, 0, true);
        view.setUint32(environ_size_ptr, 0, true);
        return 0;
      },
      
      environ_get: () => 0,
      
      args_sizes_get: (argc_ptr: number, argv_len_ptr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint32(argc_ptr, cmdArgs.length, true);
        
        let totalSize = 0;
        const encoder = new TextEncoder();
        for (const arg of cmdArgs) {
          totalSize += encoder.encode(arg).length + 1;
        }
        view.setUint32(argv_len_ptr, totalSize, true);
        return 0;
      },
      
      args_get: (argv_ptr: number, argv_buf_ptr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        const bytes = new Uint8Array(memory.buffer);
        const encoder = new TextEncoder();
        
        let currentOffset = argv_buf_ptr;
        for (let i = 0; i < cmdArgs.length; i++) {
          view.setUint32(argv_ptr + i * 4, currentOffset, true);
          const encoded = encoder.encode(cmdArgs[i]);
          bytes.set(encoded, currentOffset);
          bytes[currentOffset + encoded.length] = 0;
          currentOffset += encoded.length + 1;
        }
        return 0;
      },
      
      fd_prestat_get: (fd: number, prestat_ptr: number) => {
        if (fd === 3) {
          const memory = wasmInstance.exports.memory || wasmMemory;
          const view = new DataView(memory.buffer);
          view.setUint8(prestat_ptr, 0); // pr_type = preopen_dir (0)
          view.setUint32(prestat_ptr + 4, 1, true); // "/" length = 1
          return 0;
        }
        return 8; // EBADF
      },
      
      fd_prestat_dir_name: (fd: number, path_ptr: number, path_len: number) => {
        if (fd === 3) {
          const memory = wasmInstance.exports.memory || wasmMemory;
          const bytes = new Uint8Array(memory.buffer, path_ptr, path_len);
          bytes.set(new TextEncoder().encode("/"));
          return 0;
        }
        return 8; // EBADF
      },
      
      fd_fdstat_get: (fd: number, fdstat_ptr: number) => {
        const desc = fds.get(fd);
        if (!desc) return 8; // EBADF
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint8(fdstat_ptr, desc.path === "/" ? 3 : 4);
        view.setUint16(fdstat_ptr + 2, 0, true);
        return 0;
      },
      
      fd_write: (fd: number, iovs: number, iovs_len: number, nwrittenOutPtr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        let totalWritten = 0;
        let str = "";
        
        for (let i = 0; i < iovs_len; i++) {
          const bufPtr = view.getUint32(iovs + i * 8, true);
          const bufLen = view.getUint32(iovs + i * 8 + 4, true);
          const bytes = new Uint8Array(memory.buffer, bufPtr, bufLen);
          
          if (fd === 1 || fd === 2) {
            str += new TextDecoder().decode(bytes);
          } else {
            const desc = fds.get(fd);
            if (!desc) return 8; // EBADF
            let file = files[desc.path];
            if (!file) {
              file = { type: "file", contents: new Uint8Array(0) };
              files[desc.path] = file;
            }
            const newContents = new Uint8Array(desc.pos + bufLen);
            newContents.set(file.contents);
            newContents.set(bytes, desc.pos);
            file.contents = newContents;
            desc.pos += bufLen;
          }
          totalWritten += bufLen;
        }
        
        if (fd === 1 || fd === 2) {
          if (typeof process !== "undefined" && process.stdout && process.stdout.write) {
            process.stdout.write(str);
          } else {
            console.log(str);
          }
        }
        
        view.setUint32(nwrittenOutPtr, totalWritten, true);
        return 0;
      },
      
      fd_read: (fd: number, iovs: number, iovs_len: number, nreadOutPtr: number) => {
        const desc = fds.get(fd);
        if (!desc) return 8; // EBADF
        const file = files[desc.path];
        if (!file || file.type !== "file") return 44; // ENOENT
        
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        let totalRead = 0;
        
        for (let i = 0; i < iovs_len; i++) {
          const bufPtr = view.getUint32(iovs + i * 8, true);
          const bufLen = view.getUint32(iovs + i * 8 + 4, true);
          
          if (desc.pos >= file.contents.length) break;
          const remaining = file.contents.length - desc.pos;
          const toRead = Math.min(bufLen, remaining);
          const dest = new Uint8Array(memory.buffer, bufPtr, toRead);
          dest.set(file.contents.subarray(desc.pos, desc.pos + toRead));
          desc.pos += toRead;
          totalRead += toRead;
        }
        
        view.setUint32(nreadOutPtr, totalRead, true);
        return 0;
      },
      
      fd_seek: (fd: number, offset_low: number, offset_high: number, whence: number, newoffset_ptr: number) => {
        const desc = fds.get(fd);
        if (!desc) return 8;
        const file = files[desc.path];
        if (!file) return 8;
        
        const size = file.contents.length;
        if (whence === 0) desc.pos = offset_low;
        else if (whence === 1) desc.pos += offset_low;
        else if (whence === 2) desc.pos = size + offset_low;
        
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setUint32(newoffset_ptr, desc.pos, true);
        view.setUint32(newoffset_ptr + 4, 0, true);
        return 0;
      },
      
      fd_close: (fd: number) => {
        if (!fds.has(fd)) return 8;
        fds.delete(fd);
        return 0;
      },
      
      path_open: (dirfd: number, dirflags: number, path_ptr: number, path_len: number, oflags: number, fs_rights_base: number, fs_rights_inheriting: number, fdflags: number, fd_ptr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        const pathBytes = new Uint8Array(memory.buffer, path_ptr, path_len);
        const relPath = new TextDecoder().decode(pathBytes);
        const dirDesc = fds.get(dirfd);
        if (!dirDesc) return 8;
        const fullPath = resolvePath(dirDesc.path, relPath);
        
        const O_CREAT = (oflags & 1) !== 0;
        const O_TRUNC = (oflags & 8) !== 0;
        
        let file = files[fullPath];
        if (!file) {
          if (O_CREAT) {
            file = { type: "file", contents: new Uint8Array(0) };
            files[fullPath] = file;
          } else {
            return 44; // ENOENT
          }
        } else if (O_TRUNC) {
          file.contents = new Uint8Array(0);
        }
        
        const newFd = nextFd++;
        fds.set(newFd, { path: fullPath, pos: 0, flags: fdflags });
        view.setUint32(fd_ptr, newFd, true);
        return 0;
      },
      
      path_filestat_get: (dirfd: number, flags: number, path_ptr: number, path_len: number, stat_ptr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        const pathBytes = new Uint8Array(memory.buffer, path_ptr, path_len);
        const relPath = new TextDecoder().decode(pathBytes);
        const dirDesc = fds.get(dirfd);
        if (!dirDesc) return 8;
        const fullPath = resolvePath(dirDesc.path, relPath);
        
        const file = files[fullPath];
        if (!file) return 44;
        
        view.setUint8(stat_ptr + 16, file.type === "dir" ? 3 : 4);
        view.setBigUint64(stat_ptr + 24, BigInt(file.contents ? file.contents.length : 0), true);
        return 0;
      },
      
      random_get: (buf_ptr: number, buf_len: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const bytes = new Uint8Array(memory.buffer, buf_ptr, buf_len);
        if (typeof crypto !== "undefined" && crypto.getRandomValues) {
          crypto.getRandomValues(bytes);
        } else {
          for (let i = 0; i < buf_len; i++) bytes[i] = Math.floor(Math.random() * 256);
        }
        return 0;
      },
      
      clock_time_get: (id: number, precision: number, time_ptr: number) => {
        const memory = wasmInstance.exports.memory || wasmMemory;
        const view = new DataView(memory.buffer);
        view.setBigUint64(time_ptr, BigInt(Math.floor(performance.now() * 1e6)), true);
        return 0;
      }
    }
  };
  
  const { instance } = await WebAssembly.instantiate(buffer, imports);
  wasmInstance = instance;
  exports = instance.exports;
}

export function getExports(): WebAssembly.Exports {
  return exports;
}
const registry = new FinalizationRegistry((info: { ptr: number, type: string }) => {
  if (!exports) return;
  if (info.type === 'Collection::VarLongResult') exports.export_Collection_VarLongResult_delete(info.ptr);
  if (info.type === 'Collection::String') exports.export_Collection_String_delete(info.ptr);
  if (info.type === 'Collection::VarStringResult') exports.export_Collection_VarStringResult_delete(info.ptr);
  if (info.type === 'Xi::Deserializer') exports.export_Xi_Deserializer_delete(info.ptr);
  if (info.type === 'Xi::IMemoryDevice') exports.export_Xi_IMemoryDevice_delete(info.ptr);
  if (info.type === 'Xi::MemoryDevice') exports.export_Xi_MemoryDevice_delete(info.ptr);
  if (info.type === 'Array_u8') exports.export_Array_u8_delete(info.ptr);
  if (info.type === 'Array_String') exports.export_Array_String_delete(info.ptr);
});

function writeString(str: string): number {
  const encoder = new TextEncoder();
  const bytes = encoder.encode(str);
  const ptr = exports.alloc_buf(bytes.length + 1);
  const view = new Uint8Array(exports.memory.buffer, ptr, bytes.length + 1);
  view.set(bytes);
  view[bytes.length] = 0;
  return ptr;
}

function writeBuffer(buf: Uint8Array | string): { ptr: number, len: number } {
  const bytes = typeof buf === 'string' ? new TextEncoder().encode(buf) : buf;
  const ptr = exports.alloc_buf(bytes.length);
  const view = new Uint8Array(exports.memory.buffer, ptr, bytes.length);
  view.set(bytes);
  return { ptr, len: bytes.length };
}

function readString(ptr: number): string {
  const view = new Uint8Array(exports.memory.buffer, ptr);
  let len = 0;
  while (view[len] !== 0) len++;
  const bytes = new Uint8Array(exports.memory.buffer, ptr, len);
  return new TextDecoder().decode(bytes);
}

function readBinaryString(ptr: number, size: number): string {
  const bytes = new Uint8Array(exports.memory.buffer, ptr, size);
  let res = '';
  for (let i = 0; i < bytes.length; ++i) res += String.fromCharCode(bytes[i]);
  return res;
}

export class Array_u8 {
  ptr: number;
  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor();
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Array_u8' }, this);
      }
    } else {
      this.ptr = exports.export_Array_u8_new();
      registry.register(this, { ptr: this.ptr, type: 'Array_u8' }, this);
    }
  }

  push(val: number): void {
    exports.export_Array_u8_push(this.ptr, val);
  }

  size(): number {
    return exports.export_Array_u8_size(this.ptr);
  }

  get(index: number): number {
    return exports.export_Array_u8_get(this.ptr, index);
  }

  delete(): void {
    if (this.ptr) {
      registry.unregister(this);
      exports.export_Array_u8_delete(this.ptr);
      this.ptr = 0;
    }
  }

  toJS(): number[] {
    const arr: number[] = [];
    const sz = this.size();
    for (let i = 0; i < sz; ++i) {
      arr.push(this.get(i));
    }
    return arr;
  }

  static fromJS(arr: number[]): Array_u8 {
   const res = new Array_u8(); for (const item of arr) {
                res.push(item);
            }
            return res;  }}

export class Array_String {
  ptr: number;
  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor();
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Array_String' }, this);
      }
    } else {
      this.ptr = exports.export_Array_String_new();
      registry.register(this, { ptr: this.ptr, type: 'Array_String' }, this);
    }
  }

  push(val: string): void {
    const p = writeString(val);
    exports.export_Array_String_push(this.ptr, p);
    exports.free_buf(p);
  }

  size(): number {
    return exports.export_Array_String_size(this.ptr);
  }

  get(index: number): string {
    return readString(exports.export_Array_String_get(this.ptr, index));
  }

  delete(): void {
    if (this.ptr) {
      registry.unregister(this);
      exports.export_Array_String_delete(this.ptr);
      this.ptr = 0;
    }
  }

  toJS(): string[] {
    const arr: string[] = [];
    const sz = this.size();
    for (let i = 0; i < sz; ++i) {
      arr.push(this.get(i));
    }
    return arr;
  }

  static fromJS(arr: string[]): Array_String {
   const res = new Array_String(); for (const item of arr) {
                res.push(item);
            }
            return res;  }}

/**
 * @struct VarLongResult
 * @brief Result of a variable-length integer decoding operation.
 */
export class VarLongResult {
  ptr: number;

  constructor();
  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Collection::VarLongResult' }, this);
      }
    } else {
      if (args.length === 0) {
        this.ptr = exports.export_Collection_VarLongResult_new_default();
        registry.register(this, { ptr: this.ptr, type: 'Collection::VarLongResult' }, this);
        return;
      }
      throw new Error('No constructor overload matched given arguments');
    }
  }

  /**
   * < Decoded integer value.
   */
  get bytes(): number {
    return exports.export_Collection_VarLongResult_get_bytes(this.ptr);
  }

  set bytes(val: number) {
    exports.export_Collection_VarLongResult_set_bytes(this.ptr, val);
  }

  /**
   * < Number of bytes consumed.
   */
  get error(): boolean {
    return exports.export_Collection_VarLongResult_get_error(this.ptr) !== 0;
  }

  set error(val: boolean) {
    exports.export_Collection_VarLongResult_set_error(this.ptr, val);
  }

  delete(): void {
    if (this.ptr) {
      registry.unregister(this);
      exports.export_Collection_VarLongResult_delete(this.ptr);
      this.ptr = 0;
    }
  }

  static fromJS(obj: any): VarLongResult {
    if (obj instanceof VarLongResult) return obj;
    const res = new VarLongResult();
    if (obj.bytes !== undefined) res.bytes = obj.bytes;
    if (obj.error !== undefined) res.error = obj.error;
    return res;
  }

}

/**
 * @class String
 * @brief A mutable, COW-optimized string class inheriting from InlineArray<u8>.
 * Provides high-level string manipulation (split, replace, trim),
 * variable-length integer serialization, and numeric conversions.
 */
export class String {
  ptr: number;

  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
      }
    } else {
      if (args.length === 0) {
        this.ptr = exports.export_Collection_String_new_0();
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && typeof args[0] === 'number') {
        this.ptr = exports.export_Collection_String_new_1(args[0]);
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
        this.ptr = exports.export_Collection_String_new_2(args[0], args[1]);
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && typeof args[0] === 'string') {
        const p0 = writeString(args[0]);
        this.ptr = exports.export_Collection_String_new_3(p0);
        exports.free_buf(p0);
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && typeof args[0] === 'string') {
        const p0 = writeString(args[0]);
        this.ptr = exports.export_Collection_String_new_4(p0);
        exports.free_buf(p0);
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && (Array.isArray(args[0]) || args[0] instanceof Array_u8)) {
        const p0 = args[0] instanceof Array_u8 ? args[0] : Array_u8.fromJS(args[0]);
        const needsFree0 = !(args[0] instanceof Array_u8);
        this.ptr = exports.export_Collection_String_new_5(p0.ptr);
        if (needsFree0) p0.delete();
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && typeof args[0] === 'number') {
        this.ptr = exports.export_Collection_String_new_6(args[0]);
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && typeof args[0] === 'number') {
        this.ptr = exports.export_Collection_String_new_8(args[0]);
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      if (args.length === 1 && typeof args[0] === 'number') {
        this.ptr = exports.export_Collection_String_new_9(BigInt(args[0]));
        registry.register(this, { ptr: this.ptr, type: 'Collection::String' }, this);
        return;
      }
      throw new Error('No constructor overload matched given arguments');
    }
  }

  /**
   * @brief Returns a null-terminated C-string pointer.
   * @note May reallocate to add the null terminator.
   */
  c_str(): number;
  c_str(): number;
  c_str(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_c_str_16(this.ptr);
      return readString(resPtr);
    }
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_c_str_17(this.ptr);
      return readString(resPtr);
    }
    throw new Error('No method overload of "c_str" matched given arguments');
  }

  /**
   * @brief Returns a view/copy of a range as a String.
   */
  begin(from_: number, to: number): string;
  begin(): string;
  begin(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
      const resPtr = exports.export_Collection_String_begin_40(this.ptr, args[0], args[1]);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_begin_41(this.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "begin" matched given arguments');
  }

  toInt(): number;
  toInt(...args: any[]): any {
    if (args.length === 0) {
      const res = exports.export_Collection_String_toInt_46(this.ptr);
      return res;
    }
    throw new Error('No method overload of "toInt" matched given arguments');
  }

  shiftBool(): boolean;
  shiftBool(...args: any[]): any {
    if (args.length === 0) {
      const res = exports.export_Collection_String_shiftBool_56(this.ptr);
      return res !== 0;
    }
    throw new Error('No method overload of "shiftBool" matched given arguments');
  }

  charAt(idx: number): number;
  charAt(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const res = exports.export_Collection_String_charAt_34(this.ptr, args[0]);
      return res;
    }
    throw new Error('No method overload of "charAt" matched given arguments');
  }

  shiftVarString(): string;
  shiftVarString(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_shiftVarString_54(this.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "shiftVarString" matched given arguments');
  }

  /**
   * @brief Splits the string by a separator string.
   */
  split(sep: string): string[];
  split(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeString(args[0]);
      const resPtr = exports.export_Collection_String_split_43(this.ptr, p0);
      exports.free_buf(p0);
      const wrapper = new Array_String(resPtr, INTERNAL, true);
      const jsVal = wrapper.toJS();
      wrapper.delete();
      return jsVal;
    }
    throw new Error('No method overload of "split" matched given arguments');
  }

  length(): number;
  length(...args: any[]): any {
    if (args.length === 0) {
      const res = exports.export_Collection_String_length_18(this.ptr);
      return res;
    }
    throw new Error('No method overload of "length" matched given arguments');
  }

  from(s: number): string;
  from(buf: number): string;
  from(s: string): string;
  from(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const resPtr = exports.export_Collection_String_from_20(args[0]);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeBuffer(args[0]);
      const resPtr = exports.export_Collection_String_from_21(p0.ptr, p0.len);
      exports.free_buf(p0.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeString(args[0]);
      const resPtr = exports.export_Collection_String_from_22(p0);
      exports.free_buf(p0);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "from" matched given arguments');
  }

  pushVarString(s: string): void;
  pushVarString(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeString(args[0]);
      exports.export_Collection_String_pushVarString_53(this.ptr, p0);
      exports.free_buf(p0);
      return;
    }
    throw new Error('No method overload of "pushVarString" matched given arguments');
  }

  toUpperCase(): string;
  toUpperCase(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_toUpperCase_32(this.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "toUpperCase" matched given arguments');
  }

  padEnd(targetLen: number, padChar: number): string;
  padEnd(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
      const resPtr = exports.export_Collection_String_padEnd_37(this.ptr, args[0], args[1]);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "padEnd" matched given arguments');
  }

  includes(needle: string, start: number): boolean;
  includes(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'string' && typeof args[1] === 'number') {
      const p0 = writeString(args[0]);
      const res = exports.export_Collection_String_includes_26(this.ptr, p0, args[1]);
      exports.free_buf(p0);
      return res !== 0;
    }
    throw new Error('No method overload of "includes" matched given arguments');
  }

  create(): string;
  create(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_create_38();
      return new String(resPtr, INTERNAL, false);
    }
    throw new Error('No method overload of "create" matched given arguments');
  }

  /**
   * @brief Returns decimal representation of a binary string.
   */
  toDeci(): string;
  toDeci(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_toDeci_69(this.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "toDeci" matched given arguments');
  }

  /**
   * @brief Returns a substring.
   */
  substring(start: number, end: number): string;
  substring(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
      const resPtr = exports.export_Collection_String_substring_30(this.ptr, args[0], args[1]);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "substring" matched given arguments');
  }

  startsWith(prefix: string): boolean;
  startsWith(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeString(args[0]);
      const res = exports.export_Collection_String_startsWith_27(this.ptr, p0);
      exports.free_buf(p0);
      return res !== 0;
    }
    throw new Error('No method overload of "startsWith" matched given arguments');
  }

  check_abi(): void;
  check_abi(...args: any[]): any {
    if (args.length === 0) {
      exports.export_Collection_String_check_abi_70();
      return;
    }
    throw new Error('No method overload of "check_abi" matched given arguments');
  }

  /**
   * @brief Removes whitespace from both ends.
   */
  trim(): string;
  trim(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_trim_31(this.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "trim" matched given arguments');
  }

  unshiftVarLong(): string;
  unshiftVarLong(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_unshiftVarLong_52(this.ptr);
      return new String(resPtr, INTERNAL, false);
    }
    throw new Error('No method overload of "unshiftVarLong" matched given arguments');
  }

  peekI32(offset: number): number;
  peekI32(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const res = exports.export_Collection_String_peekI32_61(this.ptr, args[0]);
      return res;
    }
    throw new Error('No method overload of "peekI32" matched given arguments');
  }

  /**
   * @brief Decodes a VarString at an offset without moving indices.
   */
  peekVarString(offset: number): VarStringResult;
  peekVarString(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const resPtr = exports.export_Collection_String_peekVarString_68(this.ptr, args[0]);
      return new VarStringResult(resPtr, INTERNAL, true);
    }
    throw new Error('No method overload of "peekVarString" matched given arguments');
  }

  concat(other: string): void;
  concat(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeString(args[0]);
      exports.export_Collection_String_concat_13(this.ptr, p0);
      exports.free_buf(p0);
      return;
    }
    throw new Error('No method overload of "concat" matched given arguments');
  }

  toLowerCase(): string;
  toLowerCase(...args: any[]): any {
    if (args.length === 0) {
      const resPtr = exports.export_Collection_String_toLowerCase_33(this.ptr);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "toLowerCase" matched given arguments');
  }

  isEmpty(): boolean;
  isEmpty(...args: any[]): any {
    if (args.length === 0) {
      const res = exports.export_Collection_String_isEmpty_19(this.ptr);
      return res !== 0;
    }
    throw new Error('No method overload of "isEmpty" matched given arguments');
  }

  /**
   * @brief Decodes a VarLong at an offset without moving indices.
   */
  peekVarLong(offset: number): VarLongResult;
  peekVarLong(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const resPtr = exports.export_Collection_String_peekVarLong_67(this.ptr, args[0]);
      return new VarLongResult(resPtr, INTERNAL, true);
    }
    throw new Error('No method overload of "peekVarLong" matched given arguments');
  }

  /**
   * @brief Fills the string with a specific character.
   */
  fill(val: number): void;
  fill(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      exports.export_Collection_String_fill_23(this.ptr, args[0]);
      return;
    }
    throw new Error('No method overload of "fill" matched given arguments');
  }

  padStart(targetLen: number, padChar: number): string;
  padStart(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
      const resPtr = exports.export_Collection_String_padStart_36(this.ptr, args[0], args[1]);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "padStart" matched given arguments');
  }

  /**
   * @brief Replaces occurrences of a substring with another string.
   */
  replace(tgt: string, rep: string): string;
  replace(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'string' && typeof args[1] === 'string') {
      const p0 = writeString(args[0]);
      const p1 = writeString(args[1]);
      const resPtr = exports.export_Collection_String_replace_45(this.ptr, p0, p1);
      exports.free_buf(p0);
      exports.free_buf(p1);
      const strVal = readString(exports.export_String_c_str(resPtr));
      exports.export_String_delete(resPtr);
      return strVal;
    }
    throw new Error('No method overload of "replace" matched given arguments');
  }

  pushI32(v: number): string;
  pushI32(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const resPtr = exports.export_Collection_String_pushI32_59(this.ptr, args[0]);
      return new String(resPtr, INTERNAL, false);
    }
    throw new Error('No method overload of "pushI32" matched given arguments');
  }

  pushBool(v: boolean): string;
  pushBool(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'boolean') {
      const resPtr = exports.export_Collection_String_pushBool_55(this.ptr, args[0]);
      return new String(resPtr, INTERNAL, false);
    }
    throw new Error('No method overload of "pushBool" matched given arguments');
  }

  /**
   * @brief Clears the string content.
   */
  clear(): void;
  clear(...args: any[]): any {
    if (args.length === 0) {
      exports.export_Collection_String_clear_15(this.ptr);
      return;
    }
    throw new Error('No method overload of "clear" matched given arguments');
  }

  endsWith(suffix: string): boolean;
  endsWith(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'string') {
      const p0 = writeString(args[0]);
      const res = exports.export_Collection_String_endsWith_28(this.ptr, p0);
      exports.free_buf(p0);
      return res !== 0;
    }
    throw new Error('No method overload of "endsWith" matched given arguments');
  }

  /**
   * @brief Constant-time equality check for cryptographic use.
   */
  constantTimeEquals(b: string, length: number): boolean;
  constantTimeEquals(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'string' && typeof args[1] === 'number') {
      const p0 = writeString(args[0]);
      const res = exports.export_Collection_String_constantTimeEquals_48(this.ptr, p0, args[1]);
      exports.free_buf(p0);
      return res !== 0;
    }
    throw new Error('No method overload of "constantTimeEquals" matched given arguments');
  }

  shiftI32(): number;
  shiftI32(...args: any[]): any {
    if (args.length === 0) {
      const res = exports.export_Collection_String_shiftI32_60(this.ptr);
      return res;
    }
    throw new Error('No method overload of "shiftI32" matched given arguments');
  }

  charCodeAt(idx: number): number;
  charCodeAt(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const res = exports.export_Collection_String_charCodeAt_35(this.ptr, args[0]);
      return res;
    }
    throw new Error('No method overload of "charCodeAt" matched given arguments');
  }

  delete(): void {
    if (this.ptr) {
      registry.unregister(this);
      exports.export_Collection_String_delete(this.ptr);
      this.ptr = 0;
    }
  }

  static fromJS(obj: any): String {
    if (obj instanceof String) return obj;
    const res = new String();
    return res;
  }

}

/**
 * @struct VarStringResult
 * @brief Result of a variable-length string decoding/peeking operation.
 */
export class VarStringResult {
  ptr: number;

  constructor();
  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Collection::VarStringResult' }, this);
      }
    } else {
      if (args.length === 0) {
        this.ptr = exports.export_Collection_VarStringResult_new_default();
        registry.register(this, { ptr: this.ptr, type: 'Collection::VarStringResult' }, this);
        return;
      }
      throw new Error('No constructor overload matched given arguments');
    }
  }

  get value(): string {
    return readString(exports.export_Collection_VarStringResult_get_value(this.ptr));
  }

  set value(val: string) {
    const ptr = writeString(val);
    exports.export_Collection_VarStringResult_set_value(this.ptr, ptr);
    exports.free_buf(ptr);
  }

  /**
   * < Decoded string value.
   */
  get bytes(): number {
    return exports.export_Collection_VarStringResult_get_bytes(this.ptr);
  }

  set bytes(val: number) {
    exports.export_Collection_VarStringResult_set_bytes(this.ptr, val);
  }

  /**
   * < Number of bytes consumed.
   */
  get error(): boolean {
    return exports.export_Collection_VarStringResult_get_error(this.ptr) !== 0;
  }

  set error(val: boolean) {
    exports.export_Collection_VarStringResult_set_error(this.ptr, val);
  }

  delete(): void {
    if (this.ptr) {
      registry.unregister(this);
      exports.export_Collection_VarStringResult_delete(this.ptr);
      this.ptr = 0;
    }
  }

  static fromJS(obj: any): VarStringResult {
    if (obj instanceof VarStringResult) return obj;
    const res = new VarStringResult();
    if (obj.value !== undefined) res.value = obj.value;
    if (obj.bytes !== undefined) res.bytes = obj.bytes;
    if (obj.error !== undefined) res.error = obj.error;
    return res;
  }

}

/**
 * @brief Helper for deserialize inference.
 */
export class Deserializer {
  ptr: number;

  constructor();
  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Xi::Deserializer' }, this);
      }
    } else {
      if (args.length === 0) {
        this.ptr = exports.export_Xi_Deserializer_new_default();
        registry.register(this, { ptr: this.ptr, type: 'Xi::Deserializer' }, this);
        return;
      }
      throw new Error('No constructor overload matched given arguments');
    }
  }

  get data(): string {
    return readString(exports.export_Xi_Deserializer_get_data(this.ptr));
  }

  set data(val: string) {
    const ptr = writeString(val);
    exports.export_Xi_Deserializer_set_data(this.ptr, ptr);
    exports.free_buf(ptr);
  }

  delete(): void {
    if (this.ptr) {
      registry.unregister(this);
      exports.export_Xi_Deserializer_delete(this.ptr);
      this.ptr = 0;
    }
  }

  static fromJS(obj: any): Deserializer {
    if (obj instanceof Deserializer) return obj;
    const res = new Deserializer();
    if (obj.data !== undefined) res.data = obj.data;
    return res;
  }

}

/**
 * @class IMemoryDevice
 * @brief Interface for memory management devices (CPU/GPU).
 */
export class IMemoryDevice {
  ptr: number;

  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: this.ptr, type: 'Xi::IMemoryDevice' }, this);
      }
    } else {
      throw new Error('Cannot instantiate abstract class Xi::IMemoryDevice');
    }
  }

  free(handle: void): void;
  free(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      exports.export_Xi_IMemoryDevice_free_1(this.ptr, args[0]);
      return;
    }
    throw new Error('No method overload of "free" matched given arguments');
  }

  allocSurface(w: number, h: number, channels: number): void;
  allocSurface(...args: any[]): any {
    if (args.length === 3 && typeof args[0] === 'number' && typeof args[1] === 'number' && typeof args[2] === 'number') {
      const res = exports.export_Xi_IMemoryDevice_allocSurface_5(this.ptr, args[0], args[1], args[2]);
      return res;
    }
    throw new Error('No method overload of "allocSurface" matched given arguments');
  }

  view(handle: void, type_: number): void;
  view(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
      const res = exports.export_Xi_IMemoryDevice_view_4(this.ptr, args[0], args[1]);
      return res;
    }
    throw new Error('No method overload of "view" matched given arguments');
  }

  upload(handle: void, src: void, size: number): void;
  upload(...args: any[]): any {
    if (args.length === 3 && typeof args[0] === 'number' && typeof args[1] === 'number' && typeof args[2] === 'number') {
      exports.export_Xi_IMemoryDevice_upload_2(this.ptr, args[0], args[1], args[2]);
      return;
    }
    throw new Error('No method overload of "upload" matched given arguments');
  }

  alloc(size: number): void;
  alloc(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const res = exports.export_Xi_IMemoryDevice_alloc_0(this.ptr, args[0]);
      return res;
    }
    throw new Error('No method overload of "alloc" matched given arguments');
  }

  download(handle: void, dst: void, size: number): void;
  download(...args: any[]): any {
    if (args.length === 3 && typeof args[0] === 'number' && typeof args[1] === 'number' && typeof args[2] === 'number') {
      exports.export_Xi_IMemoryDevice_download_3(this.ptr, args[0], args[1], args[2]);
      return;
    }
    throw new Error('No method overload of "download" matched given arguments');
  }

}

export class MemoryDevice extends IMemoryDevice {
  constructor(ptr: number, internal: symbol, owner?: boolean);
  constructor(...args: any[]) {
    if (args.length >= 2 && args[1] === INTERNAL) {
      super(args[0], INTERNAL, false);
      this.ptr = args[0];
      const owned = args[2] !== false;
      if (owned) {
        registry.register(this, { ptr: args[0], type: 'Xi::MemoryDevice' }, this);
      }
    } else {
      throw new Error('Cannot instantiate abstract class Xi::MemoryDevice');
    }
  }

  free(handle: void): void;
  free(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      exports.export_Xi_MemoryDevice_free_1(this.ptr, args[0]);
      return;
    }
    throw new Error('No method overload of "free" matched given arguments');
  }

  allocSurface(w: number, h: number, channels: number): void;
  allocSurface(...args: any[]): any {
    if (args.length === 3 && typeof args[0] === 'number' && typeof args[1] === 'number' && typeof args[2] === 'number') {
      const res = exports.export_Xi_MemoryDevice_allocSurface_5(this.ptr, args[0], args[1], args[2]);
      return res;
    }
    throw new Error('No method overload of "allocSurface" matched given arguments');
  }

  view(handle: void, type_: number): void;
  view(...args: any[]): any {
    if (args.length === 2 && typeof args[0] === 'number' && typeof args[1] === 'number') {
      const res = exports.export_Xi_MemoryDevice_view_4(this.ptr, args[0], args[1]);
      return res;
    }
    throw new Error('No method overload of "view" matched given arguments');
  }

  upload(handle: void, src: void, size: number): void;
  upload(...args: any[]): any {
    if (args.length === 3 && typeof args[0] === 'number' && typeof args[1] === 'number' && typeof args[2] === 'number') {
      exports.export_Xi_MemoryDevice_upload_2(this.ptr, args[0], args[1], args[2]);
      return;
    }
    throw new Error('No method overload of "upload" matched given arguments');
  }

  alloc(size: number): void;
  alloc(...args: any[]): any {
    if (args.length === 1 && typeof args[0] === 'number') {
      const res = exports.export_Xi_MemoryDevice_alloc_0(this.ptr, args[0]);
      return res;
    }
    throw new Error('No method overload of "alloc" matched given arguments');
  }

  download(handle: void, dst: void, size: number): void;
  download(...args: any[]): any {
    if (args.length === 3 && typeof args[0] === 'number' && typeof args[1] === 'number' && typeof args[2] === 'number') {
      exports.export_Xi_MemoryDevice_download_3(this.ptr, args[0], args[1], args[2]);
      return;
    }
    throw new Error('No method overload of "download" matched given arguments');
  }

}

/**
 * Helpers for VarLong IO in networking
 */
export function writeVarLong(s: string, v: number): void;
export function writeVarLong(...args: any[]): any {
  if (args.length === 2 && typeof args[0] === 'string' && typeof args[1] === 'number') {
    const p0 = writeString(args[0]);
    exports.export_Xi_writeVarLong_1(p0, BigInt(args[1]));
    exports.free_buf(p0);
    return;
  }
  throw new Error('No overload of "writeVarLong" matched given arguments');
}

/**
 * Functions for numeric parsing
 */
export function parseInt(s: string): number;
export function parseInt(...args: any[]): any {
  if (args.length === 1 && typeof args[0] === 'string') {
    const p0 = writeString(args[0]);
    const res = exports.export_Collection_parseInt_0(p0);
    exports.free_buf(p0);
    return res;
  }
  throw new Error('No overload of "parseInt" matched given arguments');
}

/**
 * @brief Mixes a hash value for better distribution.
 */
export function fnvHashMix(k: number): number;
export function fnvHashMix(...args: any[]): any {
  if (args.length === 1 && typeof args[0] === 'number') {
    const res = exports.export_Xi_fnvHashMix_2(args[0]);
    return res;
  }
  throw new Error('No overload of "fnvHashMix" matched given arguments');
}

/**
 * @brief Returns current time in milliseconds.
 */
export function millis(): number;
export function millis(...args: any[]): any {
  if (args.length === 0) {
    const res = exports.export_Xi_millis_3();
    return res;
  }
  throw new Error('No overload of "millis" matched given arguments');
}

/**
 * @brief Returns current time in microseconds.
 */
export function micros(): number;
export function micros(...args: any[]): any {
  if (args.length === 0) {
    const res = exports.export_Xi_micros_4();
    return res;
  }
  throw new Error('No overload of "micros" matched given arguments');
}

