/**
 * @file JsTarget.cpp
 * @brief JavaScript target implementation: C++→WASM + TS glue generation.
 */

#include <Sew/JsTarget.hpp>
#include <Execution/Process.hpp>

namespace Sew {

using namespace Execution;

String JsTarget::cppTypeToTs(const String& cppType) {
    if (cppType == "int" || cppType == "long" || cppType == "short" ||
        cppType == "float" || cppType == "double" ||
        cppType == "i32" || cppType == "i64" || cppType == "u32" || cppType == "u64" ||
        cppType == "f32" || cppType == "f64" || cppType == "usz" ||
        cppType == "unsigned" || cppType == "size_t")
        return "number";
    if (cppType == "bool") return "boolean";
    if (cppType == "void") return "void";
    if (cppType == "char*" || cppType == "const char*" ||
        cppType == "String" || cppType == "string")
        return "string";
    return "any";
}

String JsTarget::generateTsGlue(const String& wasmContent) {
    String ts;
    ts += "// Auto-generated by Sew — TypeScript WASM bindings\n\n";
    ts += "let wasmInstance: WebAssembly.Instance;\n";
    ts += "let wasmMemory: WebAssembly.Memory;\n\n";
    ts += "export async function init(wasmUrl: string): Promise<void> {\n";
    ts += "  const response = await fetch(wasmUrl);\n";
    ts += "  const buffer = await response.arrayBuffer();\n";
    ts += "  wasmMemory = new WebAssembly.Memory({ initial: 256 });\n";
    ts += "  const imports = {\n";
    ts += "    env: { memory: wasmMemory },\n";
    ts += "    wasi_snapshot_preview1: {\n";
    ts += "      proc_exit: (code: number) => { throw new Error(`exit: ${code}`); },\n";
    ts += "      fd_write: () => 0,\n";
    ts += "      fd_seek: () => 0,\n";
    ts += "      fd_close: () => 0,\n";
    ts += "    },\n";
    ts += "  };\n";
    ts += "  const { instance } = await WebAssembly.instantiate(buffer, imports);\n";
    ts += "  wasmInstance = instance;\n";
    ts += "}\n\n";
    ts += "export function getExports(): WebAssembly.Exports {\n";
    ts += "  return wasmInstance.exports;\n";
    ts += "}\n";
    return ts;
}

LinkResult JsTarget::link(const LinkRequest& req) {
    LinkResult result;

    // Collect WASM objects and JS sources
    Array<String> wasmObjects;
    Array<String> jsSources;

    for (usz i = 0; i < req.units.size(); ++i) {
        if (!req.units[i].success) continue;
        if (req.units[i].outputPath.endsWith(".o") ||
            req.units[i].outputPath.endsWith(".wasm")) {
            wasmObjects.push(req.units[i].outputPath);
        } else {
            jsSources.push(req.units[i].outputPath);
        }
    }

    // Link WASM objects with wasm-ld
    if (wasmObjects.size() > 0) {
        String wasmOutput = req.outputPath;
        // Replace extension with .wasm
        long long dotPos = -1;
        for (usz i = 0; i < wasmOutput.size(); ++i) {
            if (wasmOutput.data()[i] == '.') dotPos = (long long)i;
        }
        if (dotPos >= 0) {
            wasmOutput = wasmOutput.substring(0, (usz)dotPos);
        }
        wasmOutput += ".wasm";

        Process ld;
        ld.file = "wasm-ld";
        ld.arg.push("--no-entry");
        ld.arg.push("--export-dynamic");
        ld.arg.push("-o");
        ld.arg.push(wasmOutput);

        for (usz i = 0; i < wasmObjects.size(); ++i) {
            ld.arg.push(wasmObjects[i]);
        }

        ld.wait();

        if (ld.exitCode != 0) {
            result.errors = "wasm-ld failed: ";
            while (ld.stderr.size() > 0)
                result.errors += ld.stderr.shift();
            return result;
        }

        // Generate TS glue
        String tsGlue = generateTsGlue("");
        String tsPath = req.outputPath;
        if (dotPos >= 0) {
            tsPath = req.outputPath.substring(0, (usz)dotPos);
        }
        tsPath += ".ts";

        // Write glue file via the same output mechanism
        result.outputPath = tsPath;
    }

    result.success = true;
    result.outputPath = req.outputPath;
    return result;
}

} // namespace Sew
