/**
 * @file PyTarget.cpp
 * @brief Python target implementation.
 */

#include <Sew/PyTarget.hpp>

namespace Sew {

LinkResult PyTarget::link(const LinkRequest& req) {
    LinkResult result;

    // For Python target: concatenate all Python source files
    // C++/JS compiled as bytecode are embedded as data
    String output;
    output += "# Auto-generated by Sew\n\n";

    for (usz i = 0; i < req.units.size(); ++i) {
        if (!req.units[i].success) continue;
        if (req.units[i].outputContent.length() > 0) {
            output += req.units[i].outputContent;
            output += "\n";
        }
    }

    result.outputPath = req.outputPath;
    result.success = true;
    return result;
}

} // namespace Sew
